#version: "3.9"

services:
  mysql:
    image: mysql:8.0.43
    command:
      - --default-authentication-plugin=mysql_native_password

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ems_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - ems-network

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$DB_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: ${BACKEND_IMAGE}
    container_name: ems-backend
    restart: always

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_URL: "jdbc:mysql://mysql:3306/ems_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC"
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      TZ: Asia/Kolkata

    volumes:
      - uploads_data:/app/uploads

    ports:
      - "8081:8081"

    networks:
      - ems-network

    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8081/actuator/health || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 90s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: ems-frontend
    restart: always

    depends_on:
      backend:
        condition: service_healthy

    ports:
      - "5173:80"

    read_only: true

    tmpfs:
      - /var/cache/nginx
      - /var/run

    networks:
      - ems-network

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 5

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql_data:
  uploads_data:

networks:
  ems-network:
    driver: bridge