  set -e
    
    mkdir -p ~/ems
    cd ~/ems
    
    ##############################################################
    # Get AWS Account ID
    ##############################################################
    
    ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    
    IMAGE_TAG="${{ needs.build-and-push.outputs.image_tag }}"
    
    BACKEND_IMAGE="$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_BACKEND }}:$IMAGE_TAG"
    
    FRONTEND_IMAGE="$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_FRONTEND }}:$IMAGE_TAG"
    
    ##############################################################
    # Create .env
    ##############################################################
    
    cat > .env <<EOF
    DB_PASSWORD=${{ secrets.DB_PASSWORD }}
    JWT_SECRET=${{ secrets.JWT_SECRET }}
    BACKEND_IMAGE=$BACKEND_IMAGE
    FRONTEND_IMAGE=$FRONTEND_IMAGE
    EOF
    
    ##############################################################
    # Login to Amazon ECR
    ##############################################################
    
    aws ecr get-login-password \
    --region ${{ secrets.AWS_REGION }} \
    | docker login \
    --username AWS \
    --password-stdin \
    $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
    
    ##############################################################
    # Pull Images
    ##############################################################
    
    docker compose \
    -f docker-compose.prod.yml \
    --env-file .env \
    pull
    
    ##############################################################
    # Restart Containers
    ##############################################################
    
    docker compose \
    -f docker-compose.prod.yml \
    --env-file .env \
    up -d --remove-orphans
    
    ##############################################################
    # Show Running Containers
    ##############################################################
    
    docker compose ps
    
    docker ps
    
    ##############################################################
    # Wait
    ##############################################################
    
    echo "Waiting for application..."
    
    sleep 40
    
    ##############################################################
    # Backend Health
    ##############################################################
    
    curl -f http://localhost:8081/actuator/health
    
    ##############################################################
    # Frontend Health
    ##############################################################
    
    curl -f http://localhost
    
    ##############################################################
    # Cleanup
    ##############################################################
    
    docker image prune -af
    
    docker builder prune -af
    
    echo "Deployment Successful"